# Haar Cascade

In [ ]:
import tensorflow as tf
from tensorflow.keras.models import load_model
import cv2
import numpy as np
import math
from tensorflow.keras.preprocessing import image
model = load_model(r'C:\Users\francis\Desktop\keras_model.h5')
body_cascade = cv2.CascadeClassifier(r"C:\Users\francis\Desktop\haarcascade_fullbody.xml")
data=[]
img=cv2.imread(r'C:\Users\francis\Desktop\pic1.png')
img = cv2.resize(img, (224,224))
X = image.img_to_array(img)
X = (X.astype(np.float32) / 255.0) 
X = np.expand_dims(X, axis=0)
preds=model.predict(X)
print(preds)
data.append(preds[0])
#rounded = [float(numpy.round(X)) for x in preds]
max_val=np.argmax(data)
print(max_val)
max_index = data.index(max_val)
#print(max_index)

In [2]:
import tensorflow as tf
from tensorflow.keras.models import load_model
import cv2
import numpy as np
import math
from tensorflow.keras.preprocessing import image
model = load_model(r'C:\Users\francis\Desktop\keras_model.h5')
body_cascade = cv2.CascadeClassifier(r"C:\Users\francis\Desktop\haarcascade_fullbody.xml")

## Real Time Detection

In [ ]:
def classify(cropped):
    data=[]
    img=cv2.imread(cropped)
    img = cv2.resize(img, (224,224))
    X = image.img_to_array(img)
    X = (X.astype(np.float32) / 255.0) 
    X = np.expand_dims(X, axis=0)
    preds=model.predict(X)
    data.append(preds[0])
    max_val=np.argmax(data)
    print(max_val)
    return max_val

def final_class(prediction):
    one="Jumping"
    two="Kicking"
    three="Running"
    four="Man with bat"
    five="Man with gun"
    six="Man with knife"
    
    #loop through predicted output, crosschecked with desired output 
    if prediction==0:
        return one
    elif prediction==1:
        return two
    elif prediction==2:
        return three  
    elif prediction==3:
        return four
    elif prediction==4:
        return five
    elif prediction==5:
        return six
    
    
cap = cv2.VideoCapture(0)

while True:
    # Get webcam images
    ret, frame = cap.read()
    
    grey_image = cv2.cvtColor(frame , cv2.COLOR_BGR2GRAY)
    
    body = body_cascade.detectMultiScale(grey_image , 1.2 , 2)
    
    for (x , y, w , h) in body:
        
        cv2.rectangle(frame, (x , y) , (x+w , y + h) , (0 , 255 , 255) , 2)
        
        cropped = frame[x:y , x+w:y + h]
        
        prediction =classify(cropped)
        print(prediction)
    
        output=final_class(prediction)
        print(output)

        #cv2.rectangle(frame, (top_left_x,top_left_y), (bottom_right_x,bottom_right_y), (0,255,0), 3)
        cv2.putText(frame, output,(50,50), cv2.FONT_HERSHEY_COMPLEX, 2 ,(0,255,0), 2)
        cv2.imshow('Object Detector using SIFT', frame)
        if cv2.waitKey(1) == 13: #13 is the Enter Key
            break

cap.release()
cv2.destroyAllWindows()

## Activity Detection 

In [37]:
def classify(cropped):
    data=[]
    img=cropped
    img = cv2.resize(img, (224,224))
    X = image.img_to_array(img)
    X = (X.astype(np.float32) / 255.0) 
    X = np.expand_dims(X, axis=0)
    preds=model.predict(X)
    data.append(preds[0])
    max_val=np.argmax(data)
    print(max_val)
    return max_val

def final_class(prediction):
    one="Jumping"
    two="Kicking"
    three="Running"
    four="Man with bat"
    five="Man with gun"
    six="Man with knife"
    
    #loop through predicted output, crosschecked with desired output 
    if prediction==0:
        return one
    elif prediction==1:
        return two
    elif prediction==2:
        return three  
    elif prediction==3:
        return four
    elif prediction==4:
        return five
    elif prediction==5:
        return six
    
    
frame = cv2.imread(r'C:\Users\francis\Desktop\run6.jpg')
print(frame)
    
grey_image = cv2.cvtColor(frame , cv2.COLOR_BGR2GRAY)
print(grey_image)
body = body_cascade.detectMultiScale(grey_image , 1.1 , 2)
print(body)
a=""   
for (x , y, w , h) in body:
        
        cv2.rectangle(frame, (x , y) , (x+w , y + h) , (0 , 255 , 255) , 2)
        
        cropped = frame[y:y+h,x:x+w]
        cv2.imshow('Object Detector', cropped)
        cv2.waitKey()
        
        
        
        prediction =classify(cropped)
        print(prediction)
    
        output=final_class(prediction)
        print(output)
        a=output

#cv2.rectangle(frame, (top_left_x,top_left_y), (bottom_right_x,bottom_right_y), (0,255,0), 3)
cv2.putText(frame, a,(20,20), cv2.FONT_HERSHEY_COMPLEX, 1 ,(0,255,0), 2)
cv2.imshow('Object Detector', frame)
cv2.waitKey()
cv2.destroyAllWindows()

[[[250 250 250]
  [250 250 250]
  [250 250 250]
  ...
  [242 232 225]
  [242 232 225]
  [242 232 225]]

 [[250 250 250]
  [250 250 250]
  [250 250 250]
  ...
  [241 231 224]
  [241 231 224]
  [241 231 224]]

 [[250 250 250]
  [250 250 250]
  [250 250 250]
  ...
  [241 231 224]
  [241 231 224]
  [241 231 224]]

 ...

 [[153 167 156]
  [163 179 168]
  [168 186 179]
  ...
  [140 127 119]
  [138 125 117]
  [144 131 123]]

 [[144 158 147]
  [171 187 176]
  [186 205 196]
  ...
  [129 116 108]
  [135 122 114]
  [154 141 133]]

 [[161 175 164]
  [183 199 188]
  [183 202 193]
  ...
  [132 120 110]
  [143 131 121]
  [167 155 145]]]
[[250 250 250 ... 231 231 231]
 [250 250 250 ... 230 230 230]
 [250 250 250 ... 230 230 230]
 ...
 [162 174 182 ... 126 124 130]
 [153 182 200 ... 115 121 140]
 [170 194 197 ... 118 129 153]]
[[479 245 155 310]
 [520 153  38  76]]
0
0
Jumping
0
0
Jumping
